package telas;

import java.awt.Toolkit;
import javax.swing.SwingConstants;

public class Tela_Principal extends javax.swing.JFrame {

    private static Livros_Acoes LA = new Livros_Acoes();
    private static Aluno_Acoes AA = new Aluno_Acoes();
    private static Menu_Ajuda MA = new Menu_Ajuda();
    
    public Tela_Principal() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/estante_icon.png")));
        setExtendedState(Tela_Principal.MAXIMIZED_BOTH);
        
        button_alunos.setVerticalTextPosition(SwingConstants.BOTTOM);
        button_alunos.setHorizontalTextPosition(SwingConstants.CENTER);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop_principal = new javax.swing.JDesktopPane();
        button_livros = new javax.swing.JButton();
        button_livros.setVerticalTextPosition(SwingConstants.BOTTOM);
        button_livros.setHorizontalTextPosition(SwingConstants.CENTER);
        button_alunos = new javax.swing.JButton();
        button_alunos.setVerticalTextPosition(SwingConstants.BOTTOM);
        button_alunos.setHorizontalTextPosition(SwingConstants.CENTER);
        button_ajuda = new javax.swing.JButton();
        button_ajuda.setVerticalTextPosition(SwingConstants.BOTTOM);
        button_ajuda.setHorizontalTextPosition(SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Biblioteca");
        setMaximumSize(new java.awt.Dimension(1920, 1080));

        button_livros.setBackground(new java.awt.Color(23, 71, 96));
        button_livros.setForeground(new java.awt.Color(255, 255, 255));
        button_livros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book_icon.png"))); // NOI18N
        button_livros.setText("Livros");
        button_livros.setToolTipText("Ações referentes a livros");
        button_livros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_livros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_livrosMouseClicked(evt);
            }
        });

        button_alunos.setBackground(new java.awt.Color(23, 71, 96));
        button_alunos.setForeground(new java.awt.Color(255, 255, 255));
        button_alunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos.png"))); // NOI18N
        button_alunos.setText("Alunos");
        button_alunos.setToolTipText("Ações referentes aos alunos");
        button_alunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_alunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_alunosMouseClicked(evt);
            }
        });

        button_ajuda.setBackground(new java.awt.Color(23, 71, 96));
        button_ajuda.setForeground(new java.awt.Color(255, 255, 255));
        button_ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ajuda_icon.png"))); // NOI18N
        button_ajuda.setText("Ajuda");
        button_ajuda.setToolTipText("Menu de ajuda ao usuário");
        button_ajuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_ajuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_ajudaMouseClicked(evt);
            }
        });

        desktop_principal.setLayer(button_livros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop_principal.setLayer(button_alunos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop_principal.setLayer(button_ajuda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktop_principalLayout = new javax.swing.GroupLayout(desktop_principal);
        desktop_principal.setLayout(desktop_principalLayout);
        desktop_principalLayout.setHorizontalGroup(
            desktop_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktop_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_alunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_livros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_ajuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        desktop_principalLayout.setVerticalGroup(
            desktop_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_livros)
                .addGap(18, 18, 18)
                .addComponent(button_alunos)
                .addGap(18, 18, 18)
                .addComponent(button_ajuda)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop_principal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_livrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_livrosMouseClicked
        if(!LA.isVisible()){
        desktop_principal.add(LA);
        LA.setVisible(true);
        }
        
    }//GEN-LAST:event_button_livrosMouseClicked

    private void button_alunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_alunosMouseClicked
        if(!AA.isVisible()){
        desktop_principal.add(AA);
        AA.setVisible(true);
        }
    }//GEN-LAST:event_button_alunosMouseClicked

    private void button_ajudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ajudaMouseClicked
        if(!MA.isVisible()){
        desktop_principal.add(MA);
        MA.setVisible(true);
        }
    }//GEN-LAST:event_button_ajudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ajuda;
    private javax.swing.JButton button_alunos;
    private javax.swing.JButton button_livros;
    private javax.swing.JDesktopPane desktop_principal;
    // End of variables declaration//GEN-END:variables
}
